# Generated by Django 6.0.3 on 2026-03-22 13:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item_default',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('weapon', 'Weapon'), ('armor', 'Armor'), ('other', 'Other')], max_length=50)),
                ('dmg_type', models.CharField(choices=[('heavy', 'Heavy'), ('light', 'Light'), ('magic', 'Magic'), ('none', 'None')], max_length=50)),
                ('lvl_req', models.IntegerField(blank=True, null=True)),
                ('dmg_base', models.IntegerField(blank=True, null=True)),
                ('armor_base', models.IntegerField(blank=True, null=True)),
                ('drop_lvl_min', models.IntegerField(blank=True, null=True)),
                ('drop_lvl_max', models.IntegerField(blank=True, null=True)),
                ('drop_rate', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
            ],
        ),
    ]
