# Generated by Django 6.0.3 on 2026-03-22 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_default',
            name='item_base_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
