# Generated by Django 6.0.3 on 2026-03-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_app', '0002_item_default_item_base_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='All_Items_Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('bonus_type', models.CharField(max_length=50)),
                ('bonus_value', models.FloatField()),
            ],
        ),
    ]
