# Generated by Django 6.0.3 on 2026-03-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_app', '0003_all_items_bonus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='all_items_bonus',
            name='bonus_value',
        ),
        migrations.AddField(
            model_name='all_items_bonus',
            name='max_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='all_items_bonus',
            name='min_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='all_items_bonus',
            name='bonus_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='all_items_bonus',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='all_items_bonus',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
