# Generated by Django 6.0.3 on 2026-03-24 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_app', '0004_remove_all_items_bonus_bonus_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_default',
            name='armor_base',
        ),
        migrations.RemoveField(
            model_name='item_default',
            name='dmg_base',
        ),
        migrations.RemoveField(
            model_name='item_default',
            name='dmg_type',
        ),
        migrations.RemoveField(
            model_name='item_default',
            name='drop_lvl_max',
        ),
        migrations.RemoveField(
            model_name='item_default',
            name='drop_lvl_min',
        ),
        migrations.RemoveField(
            model_name='item_default',
            name='drop_rate',
        ),
        migrations.CreateModel(
            name='Item_Armor_Submodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('armor_base', models.IntegerField(blank=True, null=True)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='armor_details', to='item_app.item_default')),
            ],
        ),
        migrations.CreateModel(
            name='Item_Material_Submodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type', models.CharField(blank=True, max_length=50, null=True)),
                ('rarity', models.CharField(blank=True, max_length=50, null=True)),
                ('max_stack', models.IntegerField(blank=True, default=50, null=True)),
                ('stack_able', models.BooleanField(default=True)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='material_details', to='item_app.item_default')),
            ],
        ),
        migrations.CreateModel(
            name='Item_Weapon_Submodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dmg_type', models.CharField(choices=[('heavy', 'Heavy'), ('light', 'Light'), ('magic', 'Magic'), ('none', 'None')], max_length=50)),
                ('dmg_base', models.IntegerField(blank=True, null=True)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='weapon_details', to='item_app.item_default')),
            ],
        ),
    ]
