# Generated by Django 6.0.3 on 2026-03-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_app', '0005_remove_item_default_armor_base_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_material_submodel',
            name='use_able',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item_default',
            name='category',
            field=models.CharField(choices=[('weapon', 'Weapon'), ('armor', 'Armor'), ('material', 'Material'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='item_material_submodel',
            name='material_type',
            field=models.CharField(blank=True, choices=[('upgrade', 'Upgrade'), ('crafting', 'Crafting'), ('other', 'Other')], max_length=50, null=True),
        ),
    ]
