# Generated by Django 6.0.3 on 2026-03-24 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_app', '0006_item_material_submodel_use_able_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_material_submodel',
            name='rarity',
            field=models.CharField(blank=True, choices=[('common', 'Common'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], max_length=50, null=True),
        ),
    ]
