# Generated by Django 6.0.3 on 2026-03-24 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_app', '0007_alter_item_material_submodel_rarity'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_material_submodel',
            name='price_ks',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
    ]
