# Generated by Django 6.0.3 on 2026-03-25 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_app', '0008_item_material_submodel_price_ks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_material_submodel',
            name='stack_able',
        ),
        migrations.RemoveField(
            model_name='item_material_submodel',
            name='use_able',
        ),
        migrations.AddField(
            model_name='item_default',
            name='stack_able',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='item_default',
            name='use_able',
            field=models.BooleanField(default=False),
        ),
    ]
