# Generated by Django 6.0.3 on 2026-03-25 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_app', '0009_remove_item_material_submodel_stack_able_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_material_submodel',
            name='max_stack',
        ),
        migrations.AddField(
            model_name='item_default',
            name='max_stack',
            field=models.IntegerField(blank=True, default=50, null=True),
        ),
    ]
