# Generated by Django 6.0.3 on 2026-03-25 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item_app', '0010_remove_item_material_submodel_max_stack_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_default',
            name='use_able',
        ),
    ]
