# Generated by Django 6.0.3 on 2026-03-29 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_app', '0011_remove_item_default_use_able'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_default',
            name='lvl_max_req',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
