# Generated by Django 6.0.3 on 2026-03-30 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_app', '0012_item_default_lvl_max_req'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_default',
            name='item_img_ozn',
            field=models.CharField(blank=True, default='item_default', max_length=100, null=True),
        ),
    ]
