# Generated by Django 6.0.3 on 2026-03-31 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_app', '0013_item_default_item_img_ozn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_default',
            name='category',
            field=models.CharField(choices=[('weapon', 'Weapon'), ('armor', 'Armor'), ('material', 'Material'), ('gold', 'Gold'), ('other', 'Other')], max_length=50),
        ),
    ]
