# Generated by Django 6.0.3 on 2026-04-06 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_app', '0014_alter_item_default_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item_default',
            old_name='lvl_max_req',
            new_name='shop_max_lvl_drop',
        ),
        migrations.AlterField(
            model_name='item_default',
            name='category',
            field=models.CharField(choices=[('weapon', 'Weapon'), ('armor', 'Armor'), ('material', 'Material'), ('other', 'Other')], max_length=50),
        ),
    ]
