# Generated by Django 6.0.3 on 2026-04-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_app', '0015_rename_lvl_max_req_item_default_shop_max_lvl_drop_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_default',
            name='max_stack',
        ),
        migrations.AlterField(
            model_name='item_default',
            name='item_img_ozn',
            field=models.CharField(blank=True, default='dopln_nazev_obrazku_bez_png', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item_default',
            name='lvl_req',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='item_default',
            name='shop_max_lvl_drop',
            field=models.IntegerField(blank=True, default=99, null=True),
        ),
    ]
