# Generated by Django 6.0.3 on 2026-04-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_app', '0016_remove_item_default_max_stack_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_material_submodel',
            name='material_type',
            field=models.CharField(blank=True, choices=[('upgrade', 'Upgrade'), ('crafting', 'Crafting'), ('other', 'Other')], default='upgrade', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='item_material_submodel',
            name='rarity',
            field=models.CharField(blank=True, choices=[('common', 'Common'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], default='common', max_length=50, null=True),
        ),
    ]
