# Generated by Django 6.0.3 on 2026-04-13 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_app', '0017_alter_item_material_submodel_material_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_armor_submodel',
            name='minus_attack_speed',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='item_armor_submodel',
            name='plus_hp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item_weapon_submodel',
            name='plus_attack_speed',
            field=models.FloatField(blank=True, default=1.0, null=True),
        ),
        migrations.AlterField(
            model_name='item_default',
            name='category',
            field=models.CharField(choices=[('weapon', 'Weapon'), ('armor', 'Armor'), ('helmet', 'Helmet'), ('boots', 'Boots'), ('amnulet', 'Amulet'), ('ring', 'Ring'), ('talisman', 'Talisman'), ('material', 'Material'), ('useable', 'Useable'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='item_material_submodel',
            name='material_type',
            field=models.CharField(blank=True, choices=[('upgrade', 'Upgrade'), ('crafting', 'Crafting'), ('food', 'Food'), ('quest', 'Quest'), ('rune', 'Rune'), ('useable', 'Useable'), ('spell', 'Spell'), ('other', 'Other')], default='upgrade', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Item_Amulet_Submodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_atr_bonus', models.FloatField(blank=True, default=0.0, null=True)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='amulet_details', to='item_app.item_default')),
            ],
        ),
        migrations.CreateModel(
            name='Item_Boots_Submodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('armor_base', models.IntegerField(blank=True, null=True)),
                ('plus_attack_speed', models.FloatField(blank=True, default=0.0, null=True)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='boots_details', to='item_app.item_default')),
            ],
        ),
        migrations.CreateModel(
            name='Item_Helmet_Submodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('armor_base', models.IntegerField(blank=True, null=True)),
                ('minus_attack_speed', models.FloatField(blank=True, default=0.0, null=True)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='helmet_details', to='item_app.item_default')),
            ],
        ),
        migrations.CreateModel(
            name='Item_Ring_Submodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_atr_bonus', models.FloatField(blank=True, default=0.0, null=True)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ring_details', to='item_app.item_default')),
            ],
        ),
        migrations.CreateModel(
            name='Item_Talisman_Submodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='talisman_details', to='item_app.item_default')),
            ],
        ),
    ]
