# Generated by Django 6.0.3 on 2026-04-13 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_app', '0018_item_armor_submodel_minus_attack_speed_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='all_items_bonus',
            options={'verbose_name': 'All Items Bonus', 'verbose_name_plural': 'All Items Bonuses'},
        ),
        migrations.AlterModelOptions(
            name='item_amulet_submodel',
            options={'verbose_name': 'Amulet Submodel', 'verbose_name_plural': 'Amulet Submodels'},
        ),
        migrations.AlterModelOptions(
            name='item_armor_submodel',
            options={'verbose_name': 'Armor Submodel', 'verbose_name_plural': 'Armor Submodels'},
        ),
        migrations.AlterModelOptions(
            name='item_boots_submodel',
            options={'verbose_name': 'Boots Submodel', 'verbose_name_plural': 'Boots Submodels'},
        ),
        migrations.AlterModelOptions(
            name='item_default',
            options={'verbose_name': '--- VŠECHNY ITEMY ---', 'verbose_name_plural': '--- VŠECHNY ITEMY ---'},
        ),
        migrations.AlterModelOptions(
            name='item_helmet_submodel',
            options={'verbose_name': 'Helmet Submodel', 'verbose_name_plural': 'Helmet Submodels'},
        ),
        migrations.AlterModelOptions(
            name='item_material_submodel',
            options={'verbose_name': 'Material Submodel', 'verbose_name_plural': 'Material Submodels'},
        ),
        migrations.AlterModelOptions(
            name='item_ring_submodel',
            options={'verbose_name': 'Ring Submodel', 'verbose_name_plural': 'Ring Submodels'},
        ),
        migrations.AlterModelOptions(
            name='item_talisman_submodel',
            options={'verbose_name': 'Talisman Submodel', 'verbose_name_plural': 'Talisman Submodels'},
        ),
        migrations.AlterModelOptions(
            name='item_weapon_submodel',
            options={'verbose_name': 'Weapon Submodel', 'verbose_name_plural': 'Weapon Submodels'},
        ),
        migrations.RenameField(
            model_name='item_helmet_submodel',
            old_name='minus_attack_speed',
            new_name='max_minus_attack_speed',
        ),
        migrations.RemoveField(
            model_name='item_armor_submodel',
            name='minus_attack_speed',
        ),
        migrations.AddField(
            model_name='item_armor_submodel',
            name='max_minus_attack_speed',
            field=models.FloatField(blank=True, default=0.05, null=True),
        ),
        migrations.AddField(
            model_name='item_armor_submodel',
            name='min_minus_attack_speed',
            field=models.FloatField(blank=True, default=0.01, null=True),
        ),
        migrations.AddField(
            model_name='item_helmet_submodel',
            name='min_minus_attack_speed',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
