# Generated by Django 6.0.3 on 2026-04-13 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item_app', '0019_alter_all_items_bonus_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item_boots_submodel',
            old_name='plus_attack_speed',
            new_name='plus_percent_attack_speed',
        ),
    ]
