# Generated by Django 6.0.3 on 2026-04-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_app', '0020_rename_plus_attack_speed_item_boots_submodel_plus_percent_attack_speed'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_armor_submodel',
            name='dmg_type',
            field=models.CharField(choices=[('heavy', 'Heavy'), ('light', 'Light'), ('magic', 'Magic'), ('none', 'None')], default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='item_boots_submodel',
            name='dmg_type',
            field=models.CharField(choices=[('heavy', 'Heavy'), ('light', 'Light'), ('magic', 'Magic'), ('none', 'None')], default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='item_helmet_submodel',
            name='dmg_type',
            field=models.CharField(choices=[('heavy', 'Heavy'), ('light', 'Light'), ('magic', 'Magic'), ('none', 'None')], default='none', max_length=50),
        ),
    ]
