# Generated by Django 6.0.3 on 2026-04-13 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_app', '0021_item_armor_submodel_dmg_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_default',
            name='category',
            field=models.CharField(choices=[('weapon', 'Weapon'), ('armor', 'Armor'), ('helmet', 'Helmet'), ('boots', 'Boots'), ('amnulet', 'Amulet'), ('ring', 'Ring'), ('talisman', 'Talisman'), ('pet', 'Pet'), ('material', 'Material'), ('useable', 'Useable'), ('other', 'Other')], max_length=50),
        ),
        migrations.CreateModel(
            name='Item_Pet_Submodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_pet_lvl', models.IntegerField(blank=True, default=1, null=True)),
                ('max_pet_lvl', models.IntegerField(blank=True, default=100, null=True)),
                ('min_armor_bonus', models.FloatField(blank=True, default=0.5, null=True)),
                ('max_armor_bonus', models.FloatField(blank=True, default=5.0, null=True)),
                ('min_dmg_bonus', models.FloatField(blank=True, default=1.0, null=True)),
                ('max_dmg_bonus', models.FloatField(blank=True, default=5.0, null=True)),
                ('min_hp_bonus', models.FloatField(blank=True, default=2.0, null=True)),
                ('max_hp_bonus', models.FloatField(blank=True, default=20.0, null=True)),
                ('min_prum_skoda_bonus', models.FloatField(blank=True, default=0.1, null=True)),
                ('max_prum_skoda_bonus', models.FloatField(blank=True, default=0.5, null=True)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pet_details', to='item_app.item_default')),
            ],
            options={
                'verbose_name': 'Pet Submodel',
                'verbose_name_plural': 'Pet Submodels',
            },
        ),
    ]
