# Generated by Django 6.0.3 on 2026-04-14 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_app', '0022_alter_item_default_category_item_pet_submodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_default',
            name='specific_rarity',
            field=models.CharField(blank=True, choices=[('common', 'Common'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='item_default',
            name='category',
            field=models.CharField(choices=[('weapon', 'Weapon'), ('armor', 'Armor'), ('helmet', 'Helmet'), ('boots', 'Boots'), ('amulet', 'Amulet'), ('ring', 'Ring'), ('talisman', 'Talisman'), ('pet', 'Pet'), ('material', 'Material'), ('useable', 'Useable'), ('other', 'Other')], max_length=50),
        ),
    ]
