# Generated by Django 6.0.3 on 2026-04-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_app', '0023_item_default_specific_rarity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_default',
            name='item_lvl',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
