# Generated by Django 6.0.3 on 2026-04-21 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_app', '0024_item_default_item_lvl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upgrade_Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lvl_1_amount', models.IntegerField(blank=True, null=True)),
                ('lvl_1_gold_cost', models.IntegerField(blank=True, null=True)),
                ('lvl_2_amount', models.IntegerField(blank=True, null=True)),
                ('lvl_2_gold_cost', models.IntegerField(blank=True, null=True)),
                ('lvl_3_amount', models.IntegerField(blank=True, null=True)),
                ('lvl_3_gold_cost', models.IntegerField(blank=True, null=True)),
                ('lvl_4_amount', models.IntegerField(blank=True, null=True)),
                ('lvl_4_gold_cost', models.IntegerField(blank=True, null=True)),
                ('lvl_5_amount', models.IntegerField(blank=True, null=True)),
                ('lvl_5_gold_cost', models.IntegerField(blank=True, null=True)),
                ('lvl_6_amount', models.IntegerField(blank=True, null=True)),
                ('lvl_6_gold_cost', models.IntegerField(blank=True, null=True)),
                ('lvl_7_amount', models.IntegerField(blank=True, null=True)),
                ('lvl_7_gold_cost', models.IntegerField(blank=True, null=True)),
                ('lvl_8_amount', models.IntegerField(blank=True, null=True)),
                ('lvl_8_gold_cost', models.IntegerField(blank=True, null=True)),
                ('lvl_9_amount', models.IntegerField(blank=True, null=True)),
                ('lvl_9_gold_cost', models.IntegerField(blank=True, null=True)),
                ('lvl_10_amount', models.IntegerField(blank=True, null=True)),
                ('lvl_10_gold_cost', models.IntegerField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upgrade_items', to='item_app.item_default')),
                ('lvl_10_material', models.ManyToManyField(blank=True, related_name='lvl_10_materials', to='item_app.item_default')),
                ('lvl_1_material', models.ManyToManyField(blank=True, related_name='lvl_1_materials', to='item_app.item_default')),
                ('lvl_2_material', models.ManyToManyField(blank=True, related_name='lvl_2_materials', to='item_app.item_default')),
                ('lvl_3_material', models.ManyToManyField(blank=True, related_name='lvl_3_materials', to='item_app.item_default')),
                ('lvl_4_material', models.ManyToManyField(blank=True, related_name='lvl_4_materials', to='item_app.item_default')),
                ('lvl_5_material', models.ManyToManyField(blank=True, related_name='lvl_5_materials', to='item_app.item_default')),
                ('lvl_6_material', models.ManyToManyField(blank=True, related_name='lvl_6_materials', to='item_app.item_default')),
                ('lvl_7_material', models.ManyToManyField(blank=True, related_name='lvl_7_materials', to='item_app.item_default')),
                ('lvl_8_material', models.ManyToManyField(blank=True, related_name='lvl_8_materials', to='item_app.item_default')),
                ('lvl_9_material', models.ManyToManyField(blank=True, related_name='lvl_9_materials', to='item_app.item_default')),
            ],
        ),
    ]
