# Generated by Django 6.0.3 on 2026-04-21 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_app', '0025_upgrade_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upgrade_items',
            name='lvl_10_material',
            field=models.ManyToManyField(blank=True, limit_choices_to={'item_material_submodel__material_type': 'upgrade'}, related_name='lvl_10_materials', to='item_app.item_default'),
        ),
        migrations.AlterField(
            model_name='upgrade_items',
            name='lvl_1_material',
            field=models.ManyToManyField(blank=True, limit_choices_to={'item_material_submodel__material_type': 'upgrade'}, related_name='lvl_1_materials', to='item_app.item_default'),
        ),
        migrations.AlterField(
            model_name='upgrade_items',
            name='lvl_2_material',
            field=models.ManyToManyField(blank=True, limit_choices_to={'item_material_submodel__material_type': 'upgrade'}, related_name='lvl_2_materials', to='item_app.item_default'),
        ),
        migrations.AlterField(
            model_name='upgrade_items',
            name='lvl_3_material',
            field=models.ManyToManyField(blank=True, limit_choices_to={'item_material_submodel__material_type': 'upgrade'}, related_name='lvl_3_materials', to='item_app.item_default'),
        ),
        migrations.AlterField(
            model_name='upgrade_items',
            name='lvl_4_material',
            field=models.ManyToManyField(blank=True, limit_choices_to={'item_material_submodel__material_type': 'upgrade'}, related_name='lvl_4_materials', to='item_app.item_default'),
        ),
        migrations.AlterField(
            model_name='upgrade_items',
            name='lvl_5_material',
            field=models.ManyToManyField(blank=True, limit_choices_to={'item_material_submodel__material_type': 'upgrade'}, related_name='lvl_5_materials', to='item_app.item_default'),
        ),
        migrations.AlterField(
            model_name='upgrade_items',
            name='lvl_6_material',
            field=models.ManyToManyField(blank=True, limit_choices_to={'item_material_submodel__material_type': 'upgrade'}, related_name='lvl_6_materials', to='item_app.item_default'),
        ),
        migrations.AlterField(
            model_name='upgrade_items',
            name='lvl_7_material',
            field=models.ManyToManyField(blank=True, limit_choices_to={'item_material_submodel__material_type': 'upgrade'}, related_name='lvl_7_materials', to='item_app.item_default'),
        ),
        migrations.AlterField(
            model_name='upgrade_items',
            name='lvl_8_material',
            field=models.ManyToManyField(blank=True, limit_choices_to={'item_material_submodel__material_type': 'upgrade'}, related_name='lvl_8_materials', to='item_app.item_default'),
        ),
        migrations.AlterField(
            model_name='upgrade_items',
            name='lvl_9_material',
            field=models.ManyToManyField(blank=True, limit_choices_to={'item_material_submodel__material_type': 'upgrade'}, related_name='lvl_9_materials', to='item_app.item_default'),
        ),
    ]
