# Generated by Django 6.0.3 on 2026-04-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_app', '0026_alter_upgrade_items_lvl_10_material_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item_default',
            options={'ordering': ['item_base_id'], 'verbose_name': '--- VŠECHNY ITEMY ---', 'verbose_name_plural': '--- VŠECHNY ITEMY ---'},
        ),
        migrations.AlterField(
            model_name='upgrade_items',
            name='lvl_10_material',
            field=models.ManyToManyField(blank=True, related_name='lvl_10_materials', to='item_app.item_default'),
        ),
        migrations.AlterField(
            model_name='upgrade_items',
            name='lvl_1_material',
            field=models.ManyToManyField(blank=True, related_name='lvl_1_materials', to='item_app.item_default'),
        ),
        migrations.AlterField(
            model_name='upgrade_items',
            name='lvl_2_material',
            field=models.ManyToManyField(blank=True, related_name='lvl_2_materials', to='item_app.item_default'),
        ),
        migrations.AlterField(
            model_name='upgrade_items',
            name='lvl_3_material',
            field=models.ManyToManyField(blank=True, related_name='lvl_3_materials', to='item_app.item_default'),
        ),
        migrations.AlterField(
            model_name='upgrade_items',
            name='lvl_4_material',
            field=models.ManyToManyField(blank=True, related_name='lvl_4_materials', to='item_app.item_default'),
        ),
        migrations.AlterField(
            model_name='upgrade_items',
            name='lvl_5_material',
            field=models.ManyToManyField(blank=True, related_name='lvl_5_materials', to='item_app.item_default'),
        ),
        migrations.AlterField(
            model_name='upgrade_items',
            name='lvl_6_material',
            field=models.ManyToManyField(blank=True, related_name='lvl_6_materials', to='item_app.item_default'),
        ),
        migrations.AlterField(
            model_name='upgrade_items',
            name='lvl_7_material',
            field=models.ManyToManyField(blank=True, related_name='lvl_7_materials', to='item_app.item_default'),
        ),
        migrations.AlterField(
            model_name='upgrade_items',
            name='lvl_8_material',
            field=models.ManyToManyField(blank=True, related_name='lvl_8_materials', to='item_app.item_default'),
        ),
        migrations.AlterField(
            model_name='upgrade_items',
            name='lvl_9_material',
            field=models.ManyToManyField(blank=True, related_name='lvl_9_materials', to='item_app.item_default'),
        ),
    ]
