# Generated by Django 6.0.3 on 2026-04-21 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_app', '0027_alter_item_default_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemUpgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField()),
                ('gold_cost', models.PositiveIntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upgrades', to='item_app.item_default')),
            ],
            options={
                'ordering': ['level'],
                'unique_together': {('item', 'level')},
            },
        ),
        migrations.CreateModel(
            name='UpgradeMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=1)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item_app.item_default')),
                ('upgrade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='item_app.itemupgrade')),
            ],
        ),
        migrations.DeleteModel(
            name='Upgrade_Items',
        ),
    ]
