# Generated by Django 6.0.3 on 2026-04-21 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item_app', '0028_itemupgrade_upgradematerial_delete_upgrade_items'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemupgrade',
            options={'ordering': ['lvl']},
        ),
        migrations.RenameField(
            model_name='itemupgrade',
            old_name='level',
            new_name='lvl',
        ),
        migrations.AlterUniqueTogether(
            name='itemupgrade',
            unique_together={('item', 'lvl')},
        ),
    ]
