# Generated by Django 6.0.3 on 2026-04-21 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_app', '0029_alter_itemupgrade_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemupgrade',
            name='chance',
            field=models.FloatField(blank=True, help_text='0.1 = 10%, 1=100% - AUTO DOPLNĚNÍ při DEFAULT_CHANCE = TRUE', null=True),
        ),
        migrations.AddField(
            model_name='itemupgrade',
            name='custom_chance',
            field=models.BooleanField(default=False, help_text='Použít vlastní šanci místo základní'),
        ),
        migrations.AddField(
            model_name='itemupgrade',
            name='delfault_chance',
            field=models.BooleanField(default=True, help_text='Základní nastavení (50% / lvl10)'),
        ),
        migrations.AlterField(
            model_name='itemupgrade',
            name='gold_cost',
            field=models.PositiveIntegerField(default=0, help_text='AUTOMATICKY doplněno'),
        ),
    ]
