# Generated by Django 6.0.3 on 2026-04-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_app', '0030_itemupgrade_chance_itemupgrade_custom_chance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_amulet_submodel',
            name='amulet_atr_up_koef',
            field=models.FloatField(blank=True, default=0.2, help_text='Zvyšuje se o tento procento s každou úrovní (např. 0.2 = 20%)', null=True),
        ),
        migrations.AddField(
            model_name='item_armor_submodel',
            name='armor_armor_up_koef',
            field=models.FloatField(blank=True, default=0.1, help_text='Zvyšuje se o tento procento s každou úrovní (např. 0.1 = 10%)', null=True),
        ),
        migrations.AddField(
            model_name='item_armor_submodel',
            name='armor_hp_up_koef',
            field=models.FloatField(blank=True, default=0.1, help_text='Zvyšuje se o tento procento s každou úrovní (např. 0.1 = 10%)', null=True),
        ),
        migrations.AddField(
            model_name='item_boots_submodel',
            name='boots_armor_up_koef',
            field=models.FloatField(blank=True, default=0.1, help_text='Zvyšuje se o tento procento s každou úrovní (např. 0.1 = 10%)', null=True),
        ),
        migrations.AddField(
            model_name='item_boots_submodel',
            name='boots_attack_speed_up_koef',
            field=models.FloatField(blank=True, default=0.1, help_text='Zvyšuje se o tento procento s každou úrovní (např. 0.1 = 10%)', null=True),
        ),
        migrations.AddField(
            model_name='item_helmet_submodel',
            name='helmet_armor_up_koef',
            field=models.FloatField(blank=True, default=0.1, help_text='Zvyšuje se o tento procento s každou úrovní (např. 0.1 = 10%)', null=True),
        ),
        migrations.AddField(
            model_name='item_ring_submodel',
            name='ring_atr_up_koef',
            field=models.FloatField(blank=True, default=0.2, help_text='Zvyšuje se o tento procento s každou úrovní (např. 0.2 = 20%)', null=True),
        ),
        migrations.AddField(
            model_name='item_weapon_submodel',
            name='weapon_dmg_up_koef',
            field=models.FloatField(blank=True, default=0.08, help_text='Zvyšuje se o tento procento s každou úrovní (např. 0.08 = 8%)', null=True),
        ),
    ]
