# Generated by Django 6.0.3 on 2026-05-01 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item_app', '0031_item_amulet_submodel_amulet_atr_up_koef_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item_armor_submodel',
            old_name='armor_armor_up_koef',
            new_name='armor_up_koef_ARMOR',
        ),
    ]
