# Generated by Django 6.0.3 on 2026-05-01 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item_app', '0032_rename_armor_armor_up_koef_item_armor_submodel_armor_up_koef_armor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item_armor_submodel',
            old_name='armor_hp_up_koef',
            new_name='armor_up_koef_HP',
        ),
    ]
