# Generated by Django 6.0.3 on 2026-03-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enemy_app', '0008_remove_enemy_loot_loot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dungeon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Název dungeonu')),
                ('description', models.TextField(verbose_name='Popis')),
                ('background_img', models.CharField(help_text="Název obrázku ve Flutteru (např. 'bg_dark_cave')", max_length=100)),
                ('min_level', models.IntegerField(default=1, verbose_name='Minimální úroveň pro vstup')),
                ('enemies', models.ManyToManyField(blank=True, related_name='dungeons', to='enemy_app.enemy', verbose_name='Možní nepřátelé')),
            ],
        ),
    ]
