# Generated by Django 6.0.3 on 2026-03-30 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dungeon',
            name='dungeon_base_id',
            field=models.IntegerField(default=1, unique=True, verbose_name='Dungeon Base ID'),
            preserve_default=False,
        ),
    ]
