# Generated by Django 6.0.3 on 2026-03-31 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enemy_app', '0008_remove_enemy_loot_loot'),
        ('map_app', '0002_dungeon_dungeon_base_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Void',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('void_base_id', models.IntegerField(unique=True, verbose_name='Void Base ID')),
                ('name', models.CharField(max_length=100, verbose_name='Název voidu')),
                ('description', models.TextField(verbose_name='Popis')),
                ('background_img', models.CharField(help_text="Název obrázku ve Flutteru (např. 'bg_void_realm')", max_length=100)),
                ('min_level', models.IntegerField(default=1, verbose_name='Minimální úroveň pro vstup')),
                ('enemies', models.ManyToManyField(blank=True, related_name='voids', to='enemy_app.enemy', verbose_name='Možní nepřátelé')),
            ],
        ),
        migrations.CreateModel(
            name='WorldBoss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('world_boss_base_id', models.IntegerField(unique=True, verbose_name='World Boss Base ID')),
                ('name', models.CharField(max_length=100, verbose_name='Název world bosse')),
                ('description', models.TextField(verbose_name='Popis')),
                ('background_img', models.CharField(help_text="Název obrázku ve Flutteru (např. 'bg_world_boss')", max_length=100)),
                ('min_level', models.IntegerField(default=1, verbose_name='Minimální úroveň pro vstup')),
                ('enemies', models.ManyToManyField(blank=True, related_name='world_bosses', to='enemy_app.enemy', verbose_name='Možní nepřátelé')),
            ],
        ),
    ]
