# Generated by Django 6.0.3 on 2026-04-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0003_void_worldboss'),
    ]

    operations = [
        migrations.AddField(
            model_name='dungeon',
            name='icon_img',
            field=models.CharField(blank=True, help_text="Název ikony ve Flutteru (např. 'icon_dark_cave')", max_length=100),
        ),
        migrations.AlterField(
            model_name='dungeon',
            name='background_img',
            field=models.CharField(blank=True, help_text="Název obrázku ve Flutteru (např. 'bg_dark_cave')", max_length=100),
        ),
    ]
