# Generated by Django 6.0.3 on 2026-03-20 06:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player_info',
            name='level',
        ),
        migrations.AddField(
            model_name='player_info',
            name='attack_number',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='player_info',
            name='attack_speed',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='player_info',
            name='defence_number',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='player_info',
            name='dex_base',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='player_info',
            name='dex_eqp',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='player_info',
            name='dex_max',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='player_info',
            name='dex_stats',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='player_info',
            name='gold',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='player_info',
            name='int_base',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='player_info',
            name='int_eqp',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='player_info',
            name='int_max',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='player_info',
            name='int_stats',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='player_info',
            name='luck_base',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='player_info',
            name='luck_eqp',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='player_info',
            name='luck_max',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='player_info',
            name='luck_stats',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='player_info',
            name='lvl',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='player_info',
            name='str_base',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='player_info',
            name='str_eqp',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='player_info',
            name='str_max',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='player_info',
            name='str_stats',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='player_info',
            name='vit_base',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='player_info',
            name='vit_eqp',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='player_info',
            name='vit_max',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='player_info',
            name='vit_stats',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='player_info',
            name='xp',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
