# Generated by Django 6.0.3 on 2026-03-21 06:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0002_remove_player_info_level_player_info_attack_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player_info',
            name='hp',
            field=models.IntegerField(blank=True, default=50),
        ),
        migrations.AddField(
            model_name='player_info',
            name='steps',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='player_info',
            name='steps_today',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='player_info',
            name='xp_next_lvl',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='player_info',
            name='attack_number',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='player_info',
            name='attack_speed',
            field=models.FloatField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='player_info',
            name='defence_number',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='player_info',
            name='dex_base',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='player_info',
            name='dex_max',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='player_info',
            name='int_base',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='player_info',
            name='int_max',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='player_info',
            name='luck_base',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='player_info',
            name='luck_max',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='player_info',
            name='str_base',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='player_info',
            name='str_max',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='player_info',
            name='vit_base',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='player_info',
            name='vit_max',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
