# Generated by Django 6.0.3 on 2026-03-22 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0003_player_info_hp_player_info_steps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player_info',
            name='crit_chance',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='player_info',
            name='crit_multiplier',
            field=models.FloatField(blank=True, default=1.5),
        ),
    ]
