# Generated by Django 6.0.3 on 2026-03-22 09:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0004_player_info_crit_chance_player_info_crit_multiplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='player_info',
            name='atr_points',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='player_info',
            name='skill_points',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='player_info',
            name='xp_next_lvl',
            field=models.IntegerField(default=8000, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
