# Generated by Django 6.0.3 on 2026-03-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0005_player_info_atr_points_player_info_skill_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player_info',
            name='role',
            field=models.CharField(choices=[('warrior', 'Válečník'), ('mage', 'Mág'), ('hunter', 'Hraničář')], default='warrior', max_length=10),
        ),
    ]
