# Generated by Django 6.0.3 on 2026-03-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0006_player_info_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='player_info',
            name='gender',
            field=models.CharField(choices=[('male', 'Muž'), ('female', 'Žena'), ('other', 'Jiné')], default='other', max_length=10),
        ),
    ]
