# Generated by Django 6.0.3 on 2026-03-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0007_player_info_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player_info',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Muž'), ('female', 'Žena'), ('other', 'Jiné')], default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='player_info',
            name='role',
            field=models.CharField(blank=True, choices=[('warrior', 'Válečník'), ('mage', 'Mág'), ('hunter', 'Hraničář')], default=None, max_length=10, null=True),
        ),
    ]
