# Generated by Django 6.0.3 on 2026-03-22 13:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0008_alter_player_info_gender_alter_player_info_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player_Items',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('item_status', models.CharField(choices=[('equipped', 'Equipped'), ('inventary', 'Inventory'), ('shop', 'Shop'), ('drop', 'Drop'), ('none', 'None'), ('sold', 'Sold')], default='none', max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('weapon', 'Weapon'), ('armor', 'Armor'), ('other', 'Other')], max_length=50)),
                ('dmg_type', models.CharField(choices=[('heavy', 'Heavy'), ('light', 'Light'), ('magic', 'Magic'), ('none', 'None')], max_length=50)),
                ('lvl_req', models.IntegerField(blank=True, null=True)),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], max_length=20)),
                ('price', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('dmg_min', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('dmg_max', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('dmg_avg', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('armor_base', models.IntegerField(blank=True, null=True)),
                ('armor_avg', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('drop_lvl_min', models.IntegerField(blank=True, null=True)),
                ('drop_lvl_max', models.IntegerField(blank=True, null=True)),
                ('drop_rate', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('item_stats', models.JSONField(default=dict)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='profile_app.player_info')),
            ],
        ),
    ]
