# Generated by Django 6.0.3 on 2026-03-22 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0009_player_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player_items',
            old_name='item_stats',
            new_name='item_bonus',
        ),
    ]
