# Generated by Django 6.0.3 on 2026-03-22 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0010_rename_item_stats_player_items_item_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='player_items',
            name='item_base_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
