# Generated by Django 6.0.3 on 2026-03-22 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0011_player_items_item_base_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player_items',
            old_name='armor_base',
            new_name='armor',
        ),
        migrations.RemoveField(
            model_name='player_items',
            name='armor_avg',
        ),
    ]
