# Generated by Django 6.0.3 on 2026-03-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0012_rename_armor_base_player_items_armor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player_items',
            name='item_base_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
