# Generated by Django 6.0.3 on 2026-03-22 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0013_alter_player_items_item_base_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='player_info',
            name='armor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_armor', to='profile_app.player_items'),
        ),
        migrations.AddField(
            model_name='player_info',
            name='weapon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_weapon', to='profile_app.player_items'),
        ),
    ]
