# Generated by Django 6.0.3 on 2026-03-22 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0014_player_info_armor_player_info_weapon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player_info',
            name='armor',
            field=models.BooleanField(default=False, verbose_name='Armor Equipped'),
        ),
        migrations.AlterField(
            model_name='player_info',
            name='weapon',
            field=models.BooleanField(default=False, verbose_name='Weapon Equipped'),
        ),
    ]
