# Generated by Django 6.0.3 on 2026-03-23 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0015_alter_player_info_armor_alter_player_info_weapon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player_info',
            old_name='hp',
            new_name='hp_base',
        ),
        migrations.AddField(
            model_name='player_info',
            name='hp_eqp',
            field=models.IntegerField(blank=True, default=50),
        ),
        migrations.AddField(
            model_name='player_info',
            name='hp_max',
            field=models.IntegerField(blank=True, default=50),
        ),
        migrations.AddField(
            model_name='player_info',
            name='hp_stats',
            field=models.IntegerField(blank=True, default=50),
        ),
    ]
