# Generated by Django 6.0.3 on 2026-03-23 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0016_rename_hp_player_info_hp_base_player_info_hp_eqp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player_info',
            name='hp_lvl',
            field=models.IntegerField(blank=True, default=50),
        ),
    ]
