# Generated by Django 6.0.3 on 2026-03-23 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0017_player_info_hp_lvl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player_info',
            name='hp_base',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='player_info',
            name='hp_eqp',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='player_info',
            name='hp_lvl',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='player_info',
            name='hp_max',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='player_info',
            name='hp_stats',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
