# Generated by Django 6.0.3 on 2026-03-23 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0018_alter_player_info_hp_base_alter_player_info_hp_eqp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player_info',
            name='hp_vit_koef',
            field=models.IntegerField(blank=True, default=1, verbose_name='HP Vitality Coefficient'),
        ),
    ]
