# Generated by Django 6.0.3 on 2026-03-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0019_player_info_hp_vit_koef'),
    ]

    operations = [
        migrations.AddField(
            model_name='player_info',
            name='hp_lvl_koef',
            field=models.IntegerField(blank=True, default=10, verbose_name='HP Level Coefficient'),
        ),
    ]
