# Generated by Django 6.0.3 on 2026-03-23 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0020_player_info_hp_lvl_koef'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player_info',
            old_name='attack_number',
            new_name='dmg_avg',
        ),
        migrations.AddField(
            model_name='player_info',
            name='dmg_json',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='player_info',
            name='dmg_max',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='player_info',
            name='dmg_min',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
