# Generated by Django 6.0.3 on 2026-03-23 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0021_rename_attack_number_player_info_dmg_avg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player_info',
            name='dmg_avg',
            field=models.IntegerField(blank=True, default=2),
        ),
        migrations.AlterField(
            model_name='player_info',
            name='dmg_max',
            field=models.IntegerField(blank=True, default=3),
        ),
    ]
