# Generated by Django 6.0.3 on 2026-03-23 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0022_alter_player_info_dmg_avg_alter_player_info_dmg_max'),
    ]

    operations = [
        migrations.AddField(
            model_name='player_info',
            name='dmg_base',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
