# Generated by Django 6.0.3 on 2026-03-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0023_player_info_dmg_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='player_info',
            name='dmg_atr',
            field=models.CharField(default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='player_info',
            name='dmg_atr_value',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
