# Generated by Django 6.0.3 on 2026-03-23 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0024_player_info_dmg_atr_player_info_dmg_atr_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player_info',
            name='dmg_json',
        ),
    ]
