# Generated by Django 6.0.3 on 2026-03-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0025_remove_player_info_dmg_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='player_info',
            name='hp_actual',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
