# Generated by Django 6.0.3 on 2026-03-23 14:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0026_player_info_hp_actual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player_info',
            name='defence_number',
        ),
        migrations.AddField(
            model_name='player_info',
            name='dex_resist',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AddField(
            model_name='player_info',
            name='int_resist',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AddField(
            model_name='player_info',
            name='str_resist',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(50)]),
        ),
    ]
