# Generated by Django 6.0.3 on 2026-03-23 14:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0027_remove_player_info_defence_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player_info',
            name='dex_resist',
            field=models.FloatField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='player_info',
            name='int_resist',
            field=models.FloatField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='player_info',
            name='str_resist',
            field=models.FloatField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(50)]),
        ),
    ]
