# Generated by Django 6.0.3 on 2026-03-23 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0028_alter_player_info_dex_resist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player_info',
            name='armor',
        ),
        migrations.RemoveField(
            model_name='player_info',
            name='weapon',
        ),
    ]
