# Generated by Django 6.0.3 on 2026-03-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0029_remove_player_info_armor_remove_player_info_weapon'),
    ]

    operations = [
        migrations.AddField(
            model_name='player_info',
            name='armor',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
