# Generated by Django 6.0.3 on 2026-03-23 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0030_player_info_armor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player_info',
            name='armor',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
