# Generated by Django 6.0.3 on 2026-03-24 09:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0031_alter_player_info_armor'),
    ]

    operations = [
        migrations.AddField(
            model_name='player_items',
            name='amount',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
