# Generated by Django 6.0.3 on 2026-03-24 09:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0032_player_items_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player_items',
            name='price',
        ),
        migrations.AddField(
            model_name='player_items',
            name='price_all',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='player_items',
            name='price_ks',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
