# Generated by Django 6.0.3 on 2026-03-24 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0033_remove_player_items_price_player_items_price_all_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player_items',
            name='drop_lvl_max',
        ),
        migrations.RemoveField(
            model_name='player_items',
            name='drop_lvl_min',
        ),
        migrations.RemoveField(
            model_name='player_items',
            name='drop_rate',
        ),
    ]
