# Generated by Django 6.0.3 on 2026-03-24 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0034_remove_player_items_drop_lvl_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player_items',
            name='dmg_type',
            field=models.CharField(blank=True, choices=[('heavy', 'Heavy'), ('light', 'Light'), ('magic', 'Magic'), ('none', 'None')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='player_items',
            name='item_bonus',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='player_items',
            name='rarity',
            field=models.CharField(blank=True, choices=[('common', 'Common'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], max_length=20, null=True),
        ),
    ]
