# Generated by Django 6.0.3 on 2026-03-24 10:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0035_alter_player_items_dmg_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player_Item_Material',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('item_base_id', models.IntegerField(blank=True, null=True)),
                ('item_status', models.CharField(choices=[('equipped', 'Equipped'), ('inventary', 'Inventory'), ('shop', 'Shop'), ('drop', 'Drop'), ('none', 'None'), ('sold', 'Sold')], default='none', max_length=20)),
                ('amount', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('lvl_req', models.IntegerField(blank=True, null=True)),
                ('rarity', models.CharField(blank=True, choices=[('common', 'Common'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], max_length=20, null=True)),
                ('price_ks', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('price_all', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='profile_app.player_info')),
            ],
        ),
        migrations.CreateModel(
            name='Player_Items_EQP_ABLE',
            fields=[
                ('item_base_id', models.IntegerField(blank=True, null=True)),
                ('item_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('item_status', models.CharField(choices=[('equipped', 'Equipped'), ('inventary', 'Inventory'), ('shop', 'Shop'), ('drop', 'Drop'), ('none', 'None'), ('sold', 'Sold')], default='none', max_length=20)),
                ('amount', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('dmg_type', models.CharField(blank=True, choices=[('heavy', 'Heavy'), ('light', 'Light'), ('magic', 'Magic'), ('none', 'None')], max_length=50, null=True)),
                ('lvl_req', models.IntegerField(blank=True, null=True)),
                ('rarity', models.CharField(blank=True, choices=[('common', 'Common'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], max_length=20, null=True)),
                ('price_ks', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('price_all', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('dmg_min', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('dmg_max', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('dmg_avg', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('armor', models.IntegerField(blank=True, null=True)),
                ('item_bonus', models.JSONField(blank=True, default=dict, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='profile_app.player_info')),
            ],
        ),
        migrations.DeleteModel(
            name='Player_Items',
        ),
    ]
