# Generated by Django 6.0.3 on 2026-03-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0036_player_item_material_player_items_eqp_able_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player_items_eqp_able',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
