# Generated by Django 6.0.3 on 2026-03-25 04:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0037_player_items_eqp_able_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='player_item_material',
            name='max_stack',
            field=models.IntegerField(blank=True, default=50, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='player_item_material',
            name='stack_able',
            field=models.BooleanField(default=True),
        ),
    ]
