# Generated by Django 6.0.3 on 2026-03-25 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0038_player_item_material_max_stack_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player_item_material',
            name='item_id',
        ),
        migrations.AddField(
            model_name='player_item_material',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
