# Generated by Django 6.0.3 on 2026-03-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0039_remove_player_item_material_item_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player_items_eqp_able',
            name='item_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
