# Generated by Django 6.0.3 on 2026-03-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0040_alter_player_items_eqp_able_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player_items_eqp_able',
            name='item_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
