# Generated by Django 6.0.3 on 2026-03-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0041_alter_player_items_eqp_able_item_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player_item_material',
            name='id',
        ),
        migrations.AddField(
            model_name='player_item_material',
            name='item_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
