# Generated by Django 6.0.3 on 2026-03-30 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0042_remove_player_item_material_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player_info',
            name='avatar_img_ozn',
            field=models.CharField(blank=True, default='avatar_default', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='player_info',
            name='background',
            field=models.CharField(blank=True, default='background_default', max_length=100, null=True),
        ),
    ]
