# Generated by Django 6.0.3 on 2026-03-30 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0043_player_info_avatar_img_ozn_player_info_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='player_item_material',
            name='item_img_ozn',
            field=models.CharField(blank=True, default='item_default', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='player_items_eqp_able',
            name='item_img_ozn',
            field=models.CharField(blank=True, default='item_default', max_length=100, null=True),
        ),
    ]
