# Generated by Django 6.0.3 on 2026-03-31 07:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0044_player_item_material_item_img_ozn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player_info',
            name='energy_points',
            field=models.IntegerField(default=200, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)]),
        ),
        migrations.AddField(
            model_name='player_info',
            name='energy_points_regen_5_minutes',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
