# Generated by Django 6.0.3 on 2026-03-31 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0045_player_info_energy_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player_info',
            name='action_status',
            field=models.BooleanField(default=False),
        ),
    ]
