# Generated by Django 6.0.3 on 2026-03-31 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0046_player_info_action_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player_info',
            name='action_status',
        ),
    ]
