# Generated by Django 6.0.3 on 2026-03-31 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0047_remove_player_info_action_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='player_info',
            name='busy_until',
            field=models.DateTimeField(blank=True, help_text='Čas, dokdy je hráč na výpravě nebo v s  ouboji.', null=True),
        ),
    ]
