# Generated by Django 6.0.3 on 2026-03-31 17:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0048_player_info_busy_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='player_info',
            name='dungeon_tokens',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
