# Generated by Django 6.0.3 on 2026-03-31 19:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0049_player_info_dungeon_tokens'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceStepLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=255)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('steps_claimed_today', models.IntegerField(default=0)),
            ],
        ),
    ]
