# Generated by Django 6.0.3 on 2026-03-31 19:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0050_devicesteplog'),
    ]

    operations = [
        migrations.AddField(
            model_name='player_info',
            name='last_step_sync',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
