# Generated by Django 6.0.3 on 2026-04-06 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0051_player_info_last_step_sync'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeviceStepLog',
        ),
        migrations.RemoveField(
            model_name='player_info',
            name='dungeon_tokens',
        ),
        migrations.RemoveField(
            model_name='player_info',
            name='last_step_sync',
        ),
    ]
