# Generated by Django 6.0.3 on 2026-04-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0052_delete_devicesteplog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player_info',
            name='active_status',
            field=models.BooleanField(default=False, help_text='Aktivní/Odhlášený'),
        ),
        migrations.AddField(
            model_name='player_info',
            name='ban_status',
            field=models.BooleanField(default=False, help_text='BAN: Ano/Ne.'),
        ),
        migrations.AddField(
            model_name='player_info',
            name='player_type',
            field=models.CharField(choices=[('player', 'Player'), ('bot', 'Bot'), ('test', 'Test')], default='player', max_length=10),
        ),
    ]
