# Generated by Django 6.0.3 on 2026-04-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0053_player_info_active_status_player_info_ban_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player_info',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
