# Generated by Django 6.0.3 on 2026-04-14 07:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0054_player_info_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player_item_material',
            name='max_stack',
        ),
        migrations.AddField(
            model_name='player_items_eqp_able',
            name='all_atr_bonus_amulet',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='player_items_eqp_able',
            name='all_atr_bonus_ring',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='player_items_eqp_able',
            name='attack_speed_armor',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='player_items_eqp_able',
            name='attack_speed_boots',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='player_items_eqp_able',
            name='attack_speed_helmet',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='player_items_eqp_able',
            name='attack_speed_weapon',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='player_items_eqp_able',
            name='pet_armor_bonus',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='player_items_eqp_able',
            name='pet_dmg_bonus',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='player_items_eqp_able',
            name='pet_hp_bonus',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='player_items_eqp_able',
            name='pet_lvl',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='player_items_eqp_able',
            name='pet_prum_skoda_bonus',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='player_items_eqp_able',
            name='plush_hp',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='player_items_eqp_able',
            name='shop_max_lvl_drop',
            field=models.IntegerField(blank=True, default=99, null=True),
        ),
        migrations.AddField(
            model_name='player_items_eqp_able',
            name='stack_able',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player_items_eqp_able',
            name='talisman_bonus_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='player_items_eqp_able',
            name='talisman_bonus_type',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='player_items_eqp_able',
            name='talisman_bonus_value',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='player_item_material',
            name='amount',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='player_item_material',
            name='category',
            field=models.CharField(blank=True, choices=[('weapon', 'Weapon'), ('armor', 'Armor'), ('helmet', 'Helmet'), ('boots', 'Boots'), ('amulet', 'Amulet'), ('ring', 'Ring'), ('talisman', 'Talisman'), ('pet', 'Pet'), ('material', 'Material'), ('useable', 'Useable'), ('other', 'Other')], default='material', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='player_item_material',
            name='item_status',
            field=models.CharField(choices=[('equipped', 'Equipped'), ('inventary', 'Inventory'), ('shop', 'Shop'), ('drop', 'Drop'), ('none', 'None'), ('sold', 'Sold')], default='inventary', max_length=20),
        ),
        migrations.AlterField(
            model_name='player_item_material',
            name='lvl_req',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='player_item_material',
            name='price_all',
            field=models.FloatField(blank=True, default=0.1, null=True),
        ),
        migrations.AlterField(
            model_name='player_item_material',
            name='price_ks',
            field=models.FloatField(blank=True, default=0.1, null=True),
        ),
        migrations.AlterField(
            model_name='player_item_material',
            name='rarity',
            field=models.CharField(blank=True, choices=[('common', 'Common'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], default='common', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='player_items_eqp_able',
            name='amount',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='player_items_eqp_able',
            name='category',
            field=models.CharField(blank=True, choices=[('weapon', 'Weapon'), ('armor', 'Armor'), ('helmet', 'Helmet'), ('boots', 'Boots'), ('amulet', 'Amulet'), ('ring', 'Ring'), ('talisman', 'Talisman'), ('pet', 'Pet'), ('material', 'Material'), ('useable', 'Useable'), ('other', 'Other')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='player_items_eqp_able',
            name='item_status',
            field=models.CharField(choices=[('equipped', 'Equipped'), ('inventary', 'Inventory'), ('shop', 'Shop'), ('drop', 'Drop'), ('none', 'None'), ('sold', 'Sold')], default='inventary', max_length=20),
        ),
        migrations.AlterField(
            model_name='player_items_eqp_able',
            name='lvl_req',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='player_items_eqp_able',
            name='price_all',
            field=models.FloatField(blank=True, default=0.1, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='player_items_eqp_able',
            name='price_ks',
            field=models.FloatField(blank=True, default=0.1, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
