# Generated by Django 6.0.3 on 2026-04-14 08:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0055_remove_player_item_material_max_stack_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player_info',
            old_name='background',
            new_name='player_bg_img',
        ),
        migrations.RenameField(
            model_name='player_items_eqp_able',
            old_name='plush_hp',
            new_name='plus_hp',
        ),
        migrations.RemoveField(
            model_name='player_info',
            name='energy_points_regen_5_minutes',
        ),
        migrations.AddField(
            model_name='player_info',
            name='dungeon_tokens',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='player_info',
            name='prum_skoda',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='player_info',
            name='registration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player_info',
            name='energy_points',
            field=models.IntegerField(default=200, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='player_info',
            name='steps_today',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30000)]),
        ),
    ]
