# Generated by Django 6.0.3 on 2026-04-14 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0056_rename_background_player_info_player_bg_img_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player_items_eqp_able',
            old_name='item_bonus',
            new_name='item_bonusy',
        ),
    ]
