# Generated by Django 6.0.3 on 2026-04-14 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0057_rename_item_bonus_player_items_eqp_able_item_bonusy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player_items_eqp_able',
            name='price_all',
            field=models.FloatField(blank=True, default=0.1, null=True),
        ),
        migrations.AlterField(
            model_name='player_items_eqp_able',
            name='price_ks',
            field=models.FloatField(blank=True, default=0.1, null=True),
        ),
    ]
