# Generated by Django 6.0.3 on 2026-04-14 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0058_alter_player_items_eqp_able_price_all_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player_item_material',
            name='item_status',
            field=models.CharField(choices=[('equipped', 'Equipped'), ('inventory', 'Inventory'), ('shop', 'Shop'), ('drop', 'Drop'), ('none', 'None'), ('sold', 'Sold')], default='inventory', max_length=20),
        ),
        migrations.AlterField(
            model_name='player_items_eqp_able',
            name='item_status',
            field=models.CharField(choices=[('equipped', 'Equipped'), ('inventory', 'Inventory'), ('shop', 'Shop'), ('drop', 'Drop'), ('none', 'None'), ('sold', 'Sold')], default='inventory', max_length=20),
        ),
    ]
