# Generated by Django 6.0.3 on 2026-04-18 14:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0059_alter_player_item_material_item_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player_info',
            name='mana_base',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='player_info',
            name='mana_eqp',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='player_info',
            name='mana_lvl',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='player_info',
            name='mana_lvl_koef',
            field=models.IntegerField(blank=True, default=5, verbose_name='Mana Level Coefficient'),
        ),
        migrations.AddField(
            model_name='player_info',
            name='mana_max',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='player_info',
            name='mana_stats',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='player_info',
            name='prec_base',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='player_info',
            name='prec_eqp',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='player_info',
            name='prec_max',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='player_info',
            name='prec_stats',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='player_info',
            name='energy_points',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
