# Generated by Django 6.0.3 on 2026-04-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0060_player_info_mana_base_player_info_mana_eqp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player_items_eqp_able',
            name='item_lvl',
            field=models.IntegerField(default=0),
        ),
    ]
