# Generated by Django 6.0.3 on 2026-04-21 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0061_player_items_eqp_able_item_lvl'),
    ]

    operations = [
        migrations.AddField(
            model_name='player_info',
            name='mana_int_koef',
            field=models.IntegerField(blank=True, default=1, verbose_name='Mana Intelligence Coefficient'),
        ),
        migrations.AlterField(
            model_name='player_item_material',
            name='item_status',
            field=models.CharField(choices=[('equipped', 'Equipped'), ('inventory', 'Inventory'), ('drop', 'Drop'), ('none', 'None'), ('sold', 'Sold')], default='inventory', max_length=20),
        ),
        migrations.AlterField(
            model_name='player_items_eqp_able',
            name='item_status',
            field=models.CharField(choices=[('equipped', 'Equipped'), ('inventory', 'Inventory'), ('drop', 'Drop'), ('none', 'None'), ('sold', 'Sold')], default='inventory', max_length=20),
        ),
    ]
