# Generated by Django 6.0.3 on 2026-04-21 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0062_player_info_mana_int_koef_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player_items_eqp_able',
            name='amulet_atr_up_koef',
            field=models.FloatField(blank=True, default=0.2, help_text='Zvyšuje se o tento procento s každou úrovní (např. 0.2 = 20%)', null=True),
        ),
        migrations.AddField(
            model_name='player_items_eqp_able',
            name='armor_armor_up_koef',
            field=models.FloatField(blank=True, default=0.1, help_text='Zvyšuje se o tento procento s každou úrovní (např. 0.1 = 10%)', null=True),
        ),
        migrations.AddField(
            model_name='player_items_eqp_able',
            name='armor_hp_up_koef',
            field=models.FloatField(blank=True, default=0.1, help_text='Zvyšuje se o tento procento s každou úrovní (např. 0.1 = 10%)', null=True),
        ),
        migrations.AddField(
            model_name='player_items_eqp_able',
            name='boots_armor_up_koef',
            field=models.FloatField(blank=True, default=0.1, help_text='Zvyšuje se o tento procento s každou úrovní (např. 0.1 = 10%)', null=True),
        ),
        migrations.AddField(
            model_name='player_items_eqp_able',
            name='boots_attack_speed_up_koef',
            field=models.FloatField(blank=True, default=0.1, help_text='Zvyšuje se o tento procento s každou úrovní (např. 0.1 = 10%)', null=True),
        ),
        migrations.AddField(
            model_name='player_items_eqp_able',
            name='helmet_armor_up_koef',
            field=models.FloatField(blank=True, default=0.1, help_text='Zvyšuje se o tento procento s každou úrovní (např. 0.1 = 10%)', null=True),
        ),
        migrations.AddField(
            model_name='player_items_eqp_able',
            name='ring_atr_up_koef',
            field=models.FloatField(blank=True, default=0.2, help_text='Zvyšuje se o tento procento s každou úrovní (např. 0.2 = 20%)', null=True),
        ),
        migrations.AddField(
            model_name='player_items_eqp_able',
            name='weapon_dmg_up_koef',
            field=models.FloatField(blank=True, default=0.08, help_text='Zvyšuje se o tento procento s každou úrovní (např. 0.08 = 8%)', null=True),
        ),
    ]
