# Generated by Django 6.0.3 on 2026-04-27 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0063_player_items_eqp_able_amulet_atr_up_koef_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player_item_material',
            name='price_all',
            field=models.FloatField(blank=True, default=0.1, help_text='POČÍTÁ SE AUTOMATICKY', null=True),
        ),
    ]
