# Generated by Django 6.0.3 on 2026-05-01 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0064_alter_player_item_material_price_all'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player_items_eqp_able',
            old_name='armor_armor_up_koef',
            new_name='armor_up_koef_ARMOR',
        ),
    ]
