# Generated by Django 6.0.3 on 2026-05-01 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0065_rename_armor_armor_up_koef_player_items_eqp_able_armor_up_koef_armor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player_items_eqp_able',
            old_name='armor_hp_up_koef',
            new_name='armor_up_koef_HP',
        ),
    ]
