# Generated by Django 6.0.3 on 2026-03-23 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enemy_app', '0004_enemy_hp_actual'),
        ('profile_app', '0026_player_info_hp_actual'),
    ]

    operations = [
        migrations.CreateModel(
            name='fight_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner', models.CharField(max_length=100)),
                ('time_start', models.DateTimeField()),
                ('time_end', models.DateTimeField()),
                ('turn_logs', models.JSONField(default=list)),
                ('enemy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enemy_app.enemy')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_app.player_info')),
            ],
        ),
    ]
