# Generated by Django 6.0.3 on 2026-03-31 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fight_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fight_log',
            old_name='winner',
            new_name='defeinitive_winner',
        ),
        migrations.RemoveField(
            model_name='fight_log',
            name='enemy',
        ),
        migrations.AddField(
            model_name='fight_log',
            name='all_enemies_defeded',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='fight_log',
            name='time_duration_seconds',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
