# Generated by Django 6.0.3 on 2026-03-23 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('id_unique', models.AutoField(primary_key=True, serialize=False)),
                ('id_base', models.IntegerField(unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('lvl', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, choices=[('Boss', 'Boss'), ('Void', 'Void'), ('Mob', 'Mob')], max_length=100, null=True)),
                ('spawn_option', models.BooleanField(blank=True, null=True)),
                ('hp', models.IntegerField(blank=True, null=True)),
                ('hp_regen', models.FloatField(blank=True, null=True)),
                ('armor', models.IntegerField(blank=True, null=True)),
                ('dmg_min', models.IntegerField(blank=True, null=True)),
                ('dmg_max', models.IntegerField(blank=True, null=True)),
                ('attack_speed', models.FloatField(blank=True, null=True)),
                ('critical_chance', models.FloatField(blank=True, null=True)),
                ('critical_multiplier', models.FloatField(blank=True, null=True)),
                ('loot', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
