# Generated by Django 6.0.3 on 2026-03-23 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enemy_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enemy',
            old_name='hp_regen',
            new_name='hp_regen_5s',
        ),
    ]
