# Generated by Django 6.0.3 on 2026-03-23 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enemy_app', '0002_rename_hp_regen_enemy_hp_regen_5s'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemy',
            name='init_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
