# Generated by Django 6.0.3 on 2026-03-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enemy_app', '0003_enemy_init_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemy',
            name='hp_actual',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
