# Generated by Django 6.0.3 on 2026-03-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enemy_app', '0004_enemy_hp_actual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enemy',
            name='critical_chance',
        ),
        migrations.RemoveField(
            model_name='enemy',
            name='critical_multiplier',
        ),
        migrations.AddField(
            model_name='enemy',
            name='crit_chance',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='enemy',
            name='crit_multiplier',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
    ]
