# Generated by Django 6.0.3 on 2026-03-23 15:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enemy_app', '0005_remove_enemy_critical_chance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemy',
            name='dex_resist',
            field=models.FloatField(blank=True, default=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AddField(
            model_name='enemy',
            name='int_resist',
            field=models.FloatField(blank=True, default=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AddField(
            model_name='enemy',
            name='str_resist',
            field=models.FloatField(blank=True, default=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)]),
        ),
    ]
