# Generated by Django 6.0.3 on 2026-03-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enemy_app', '0006_enemy_dex_resist_enemy_int_resist_enemy_str_resist'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemy',
            name='dmg_atr',
            field=models.CharField(blank=True, choices=[('str', 'str'), ('dex', 'dex'), ('int', 'int')], max_length=10, null=True),
        ),
    ]
