# Generated by Django 6.0.3 on 2026-03-24 09:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enemy_app', '0007_enemy_dmg_atr'),
        ('item_app', '0005_remove_item_default_armor_base_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enemy',
            name='loot',
        ),
        migrations.CreateModel(
            name='loot',
            fields=[
                ('id_unique', models.AutoField(primary_key=True, serialize=False)),
                ('drop_rate', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('drop_max_amount', models.IntegerField(blank=True, default=1, null=True)),
                ('enemy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loot_enemy', to='enemy_app.enemy')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loot_items', to='item_app.item_default')),
            ],
        ),
    ]
