# Generated by Django 6.0.3 on 2026-03-31 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enemy_app', '0008_remove_enemy_loot_loot'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemy',
            name='enemy_img_ozn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
