# Generated by Django 6.0.3 on 2026-03-31 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enemy_app', '0009_enemy_enemy_img_ozn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enemy',
            old_name='hp',
            new_name='hp_max',
        ),
    ]
