# Generated by Django 6.0.3 on 2026-03-31 15:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enemy_app', '0010_rename_hp_enemy_hp_max'),
    ]

    operations = [
        migrations.CreateModel(
            name='loot_gold',
            fields=[
                ('id_unique', models.AutoField(primary_key=True, serialize=False)),
                ('drop_rate', models.FloatField(default=80, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('drop_min_amount', models.IntegerField(blank=True, default=1, null=True)),
                ('drop_max_amount', models.IntegerField(blank=True, default=5, null=True)),
                ('enemy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loot_gold_enemy', to='enemy_app.enemy')),
            ],
        ),
    ]
