# Generated by Django 6.0.3 on 2026-04-07 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enemy_app', '0011_loot_gold'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enemy',
            old_name='init_name',
            new_name='enemy_name',
        ),
    ]
