# Generated by Django 6.0.3 on 2026-04-07 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enemy_app', '0012_rename_init_name_enemy_enemy_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enemy',
            old_name='enemy_name',
            new_name='init_name',
        ),
    ]
