# Generated by Django 6.0.3 on 2026-04-13 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enemy_app', '0013_rename_enemy_name_enemy_init_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enemy',
            old_name='hp_actual',
            new_name='hp_actual_AUTO',
        ),
        migrations.RenameField(
            model_name='enemy',
            old_name='hp_regen_5s',
            new_name='hp_regen_5s_AUTO',
        ),
        migrations.RenameField(
            model_name='enemy',
            old_name='init_name',
            new_name='init_name_AUTO',
        ),
        migrations.AlterField(
            model_name='enemy',
            name='category',
            field=models.CharField(blank=True, choices=[('Boss', 'Boss'), ('Vortex Guardian', 'Vortex Guardian'), ('Mob', 'Mob')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='enemy',
            name='crit_multiplier',
            field=models.FloatField(blank=True, default=1.5, null=True),
        ),
    ]
