# Generated by Django 6.0.3 on 2026-04-13 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enemy_app', '0014_rename_hp_actual_enemy_hp_actual_auto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enemy',
            name='category',
            field=models.CharField(blank=True, choices=[('Boss', 'Boss'), ('Mini-Boss', 'Mini-Boss'), ('Vortex Guardian', 'Vortex Guardian'), ('Mob', 'Mob')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loot_gold',
            name='drop_max_amount',
            field=models.FloatField(blank=True, default=5, null=True),
        ),
        migrations.AlterField(
            model_name='loot_gold',
            name='drop_min_amount',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
    ]
